name: Update Nix Flake

on:
  schedule:
    # Runs at 00:00 Sunday AEST (which is 14:00 Saturday UTC)
    - cron: '0 14 * * 6'
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake
        run: nix flake update

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git add flake.lock
            git commit -m 'chore: update flake.lock [automated]' || echo 'No changes to commit'
            git push
          else
            echo 'No changes to commit.'
          fi
